#+TITLE: Email (via mu4e)
#+AUTHOR: Dave Voutila
#+EMAIL: voutilad@gmail.com

* TODO Configure System Packages
   This needs to sanity checking, but for =OpenBSD= I think we need at
   least the following copmonents.

** TODO mbsync
   Really from the package =isync=. It handles IMAP synchronization
   for us.

   #+BEGIN_SRC shell
     doas pkg_add isync
   #+END_SRC

   It needs some dual-mailbox configuration (see <reference .mbsyncrc
   in dotfiles>).

** mu
   It provides the Emacs package =mu4e=, but we need the critical
   system program that builds the index behind the scenes.

   #+BEGIN_SRC shell
     doas pkg_add mu
   #+END_SRC

* mu4e
  This config gets rather complicated, so I'm breaking it down a bit.

** Install =mu4e=

  Now we're going to install the package and configure the simple
  stuff. First our default email name/address then our basic =mu4e=
  settings.

  #+BEGIN_SRC emacs-lisp
    (setq user-mail-address "voutilad@gmail.com"
          user-full-name "Dave Voutila")
  #+END_SRC

  Since =mu4e= installs as part of the system package, all we need to
  do is require it. (Unless we're using Homebrew on macOS.)

  #+BEGIN_SRC emacs-lisp
    (if (eq system-type 'darwin)
        (add-to-list 'load-path (expand-file-name "vendor/mu4e" user-emacs-directory)))

    (if (not (eq window-system 'w32))
        (require 'mu4e))

    (setq mu4e-maildir (expand-file-name "~/.mail")
          mu4e-attachment-dir "~/Downloads"
          mu4e-get-mail-command "mbsync gmail sisu"
          mu4e-update-interval 300)
  #+END_SRC

** Contexts
   We use /contexts/ to switch between different email accounts for
   sending purposes. I'm still getting my head around this, but this
   has been somewhat working so far.

   #+BEGIN_SRC emacs-lisp
     (if (not (eq window-system 'w32))
         (setq mu4e-contexts
               `(, (make-mu4e-context
                    :name "Gmail"
                    :enter-func (lambda () (mu4e-message "Entering Gmail context"))
                    :leave-func (lambda () (mu4e-message "Leaving Gmail context"))
                    :match-func (lambda (msg)
                                  (when msg
                                    (mu4e-message-contact-field-matches msg
                                                                        :to "voutilad@gmail.com")))
                    :vars '( ( user-mail-address      . "voutilad@gmail.com"  )
                             ( user-full-name         . "Dave Voutila" )
                             ( mu4e-compose-signature .
                                                      (concat "Dave\n"))))
                   , (make-mu4e-context
                      :name "Sisu"
                      :enter-func (lambda () (mu4e-message "Entering Sisu context"))
                      :leave-func (lambda () (mu4e-message "Leaving Sisu context"))
                      :match-func (lambda (msg)
                                    (when msg
                                      (mu4e-message-contact-field-matches msg
                                                                          :to "dave@sisu.io")))
                      :vars '( ( user-mail-address      . "dave@sisu.io")
                               ( user-full-name         . "Dave Voutila")
                               ( mu4e-compose-signature .
                                                        (concat "Dave Voutila\n"
                                                                "+1 617-538-2151\n"
                                                                "Sisu Integrated Services, LLC\n")))))))
   #+END_SRC

** Bookmarks
   Since =mu4e= uses search queries to dictate your view into your
   mail, it helps to make some bookmarks for commonly used searches.

   #+BEGIN_SRC emacs-lisp
     (if (not (eq window-system 'w32))
         (setq mu4e-bookmarks
               `( ,(make-mu4e-bookmark
                    :name  "Unread Messages"
                    :query "flag:unread AND NOT flag:trashed"
                    :key ?u)
                  ,(make-mu4e-bookmark
                    :name "Today's Messages"
                    :query "date:today..now"
                    :key ?t)
                  ,(make-mu4e-bookmark
                    :name  "Work Email"
                    :query "to:dave@sisu.io"
                    :key ?w)
                  ,(make-mu4e-bookmark
                    :name  "Personal Email"
                    :query "to:voutilad@gmail.com"
                    :key ?p)
                  ,(make-mu4e-bookmark
                    :name "Personal Trash"
                    :query "to:voutilad@gmail.com AND flag:trashed"
                    :key ?t))))
   #+END_SRC
